<?xml version="1.0"?>
<robot name="square_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo reference="caster_wheel_link">
    <mu1 value="0.0"/>
    <mu2 value="0.0"/>
  </gazebo>
  
  <gazebo reference="caster_wheel_link2">
    <mu1 value="0.0"/>
    <mu2 value="0.0"/>
  </gazebo>

  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
      <left_joint>base_left_wheel_joint</left_joint>
      <right_joint>base_right_wheel_joint</right_joint>
      <wheel_separation>${base_width + wheel_length/2.0}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>

      <odometry_topic>/${robot_name}/odom</odometry_topic>

    </plugin>
  </gazebo>
  
  <gazebo>
    <plugin filename="gz-sim-velocity-control-system"
            name="gz::sim::systems::VelocityControl">
      <!-- <left_joint>base_left_wheel_joint</left_joint>
      <right_joint>base_right_wheel_joint</right_joint>
      <wheel_separation>0.45</wheel_separation>
      <wheel_radius>0.1</wheel_radius>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
      <topic>/model/${robot_name}/cmd_vel</topic> -->
    </plugin>
  </gazebo>
  

  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
      <joint_name>base_left_wheel_joint</joint_name>
      <joint_name>base_right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

   <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>10</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <topic>/${robot_name}/scan</topic>
      <gz_frame_id>lidar_link</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>50.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>
  
   <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>/${robot_name}/imu</topic>
      <imu>
        <noise>
          <type>gaussian</type>
          <!-- Noise characteristics for accelerometer -->
          <rate>
            <mean>0.0</mean>
            <stddev>0.0002</stddev>
            <bias_mean>0.0</bias_mean>
            <bias_stddev>0.0</bias_stddev>
          </rate>
          <!-- Noise characteristics for gyroscope -->
          <accel>
            <mean>0.0</mean>
            <stddev>0.017</stddev>
            <bias_mean>0.0</bias_mean>
            <bias_stddev>0.0</bias_stddev>
          </accel>
        </noise>
      </imu>
    </sensor>
  </gazebo>
  
</robot>


